### ISSUE TITLE
Deployment of ramayana alignment

### ISSUE THREAD

**Issue by gasyoun** [avinashvarna/rAmAyaNa-paThanam#1]
What does that mean, @avinashvarna please tell ?
See my http://samskrtam.ru/parallel-corpus/

**Comment by avinashvarna** [comment]
Thanks for sharing the link - this is similar to valmikiramayan.net in Russian. Will be useful for training multi-lingual models.

This repo though is for a demo of aligning *audio* with text to create a "read along" mode. I was planning to send a note in the Sanskrit programmers mailing list later this week with more details, but you can take a sneak peek here - https://avinashvarna.github.io/rAmAyaNa-paThanam/

If you play the audio at the top of the page, the corresponding word being uttered should be highlighted (with some occasional lag/errors). Scrolling to a different point in the audio should cause the text to also advance to the corresponding section.

**Comment by avinashvarna** [comment]
Hope that was clear. Closing this issue.
